reduce rendering from mousewheel zoom and pan
throughout :
add this._super(...arguments) to those lifecycle event functions which did not have it, and change the order of others to ensure that it is called first (or last for willDestroy*).

various uses of compareDependencies() to track cause of CP updates : axis-2d.js : trackBlocks, willRender, axis-tracks.js : tracksTree, block.js : featuresCountIncludingZoom, isZoomedOut.
(slowDependenciesEffect() : slowDependenciesEffectDependencies  could also have been implemented via compareDependencies()).  These can be dropped as this branch is completed.

axis-1d.hbs : don't expose .domainChanged, .scaleChanged.
axis-1d.js : updateAxis() : wrap stacksAdjust() in updateAxisTask, with .keepLatest().
axis-tracks.js : split showTrackBlocksTask from showTrackBlocks to throttle it, with .keepLatest().

axis-1d.js : domainChanged() : depend on .zoomedDomainThrottled instead of .domain
block.js : featureCountInZoom() : if ! .zoomed then use .featureCount directly.
axisBrush.js : zoom() : Because ember-raf-scheduler is not updated, call axisScaleChanged() directly; this does not debounce, so axis scale is in sync with mouse-wheel zoom and ticks;  don't use a transition if isWheelEvent.
package.json : upgrade ember-ajax : ^5.0.0 -> ^5.1.2, to solve : TypeError: _runloop.run.join is not a function.